### ISSUE TITLE
Error when refining

### ISSUE THREAD

**Issue by jliptrap** [msuperdock/vim-agda#5]
Lately I've been regularly getting errors like:

```
Error detected while processing function <SNR>70_handle_event[8]..<SNR>70_handle_line[61]..<SNR>70_handle_points[1]..<lambda>511[1]..<SNR>70_handle_point:                                                                                                                                                                
line    1:
E684: list index out of range: 0
```

But I don't have a minimal repro yet.  Thanks!

**Comment by msuperdock** [comment]
It looks like this issue was introduced by b29d579--I rewrote the `handle_points` function to use the ranges given by Agda rather than scanning the file for holes. This should work in principle, but Agda sometimes sends empty ranges. I think this is an Agda bug, so I've opened an issue: https://github.com/agda/agda/issues/5808

In the meantime, I've written a fix (1695060); now vim-agda will use the ranges given by Agda only if they are all non-empty.
